spring:
    mail:
        host: smtp.gmail.com
        port: 465
        username: sean@fonk-amsterdam.com
        password: emnlxsahlnjpmcsu
        test-connection: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
        protocol: smtps